### ISSUE TITLE
Invalid login attempt (username or password)

### ISSUE THREAD

**Issue by TechSolomon** [AndrewPlayer3/VideoSite_CS372#20]
Account does not exist – `Cannot read properties of null (reading 'password')`

Incorrect password – `CredentialsSignin`

**Comment by TechSolomon** [comment]
Improved error messages (text as video length) – `video_length must be a `number` type, but the final value was: `NaN` (cast from the value `" "`).`

**Comment by AndrewPlayer3** [comment]
Now says 'Incorrect Username or Password.'
