### ISSUE TITLE
Special characters for `?text_query=`

### ISSUE THREAD

**Issue by TechSolomon** [AndrewPlayer3/VideoSite_CS372#21]
Edge cases:
- `*`
- (
- )
- ()

-----

```
Server Error

Error: Error serializing `.videos` returned from `getServerSideProps` in "/".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
```

**Comment by benstream** [comment]
Additional Characters   found
- [
- ]
- ?

**Comment by TechSolomon** [comment]
Improved error messages (text as video length) – ```video_length must be a `number` type, but the final value was: `NaN` (cast from the value `" "`).```

**Comment by TechSolomon** [comment]
Response code for invalid video ID (e.g. `videos/*`)

**Comment by AndrewPlayer3** [comment]
Should be fixed now 🤞
